version: '3.2'
networks:
  app-internal: 
  public:
    external:
      name: traefik_webgateway
secrets:
  db_host:
    file: ./secrets/db_host
  db_name:
    file: ./secrets/db_name
  db_port:
    file: ./secrets/db_port
  db_root_password:
    file: ./secrets/db_root_password
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  sf_secret_key:
    file: ./secrets/sf_secret_key
volumes:
  dashtainer-db-datastore:
services:
  mariadb:
    image: mariadb:10.1
    secrets:
      - db_host
      - db_name
      - db_port
      - db_root_password
      - db_user
      - db_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_name
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    networks:
      - app-internal
    ports:
      - '3600:3306'
    restart: always
    volumes:
      - "dashtainer-db-datastore:/var/lib/mysql:delegated"
      - "$PWD/mariadb/config-file.cnf:/etc/mysql/conf.d/config-file.cnf:delegated"
      - "$PWD/mariadb/my.cnf:/etc/mysql/my.cnf:delegated"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        SYSTEM_PACKAGES: ''
    labels:
      - traefik.backend={$COMPOSE_PROJECT_NAME}_nginx
      - traefik.docker.network=traefik_webgateway
      - 'traefik.frontend.rule=Host:dashtainer.localhost'
    networks:
      - app-internal
      - public
    volumes:
      - "$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated"
      - "$PWD/nginx/core.conf:/etc/nginx/conf.d/core.conf:delegated"
      - "$PWD/nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:delegated"
      - "$PWD/nginx/vhost.conf:/etc/nginx/sites-available/default:delegated"
      - "$PWD/../:/var/www:delegated"
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        SYSTEM_PACKAGES: ''
        PHP_PACKAGES: 'php7.2-fpm php7.2-cli php7.2-curl php7.2-intl php7.2-json php7.2-mbstring php7.2-mysql php7.2-opcache php7.2-xml php-pear php7.2-zip php-xdebug'
        PEAR_PACKAGES: ''
        PECL_PACKAGES: ''
        COMPOSER_INSTALL: '1'
        BLACKFIRE_INSTALL: 0
    secrets:
      - db_host
      - db_name
      - db_port
      - db_user
      - db_password
      - sf_secret_key
    networks:
      - app-internal
    volumes:
      - "$PWD/php/php.ini:/etc/php/7.2/fpm/conf.d/zzzz_custom.ini:delegated"
      - "$PWD/php/php-cli.ini:/etc/php/7.2/cli/conf.d/zzzz_custom.ini:delegated"
      - "$PWD/php/xdebug.ini:/etc/php/7.2/fpm/conf.d/zzzz_xdebug.ini:delegated"
      - "$PWD/php/xdebug-cli.ini:/etc/php/7.2/cli/conf.d/zzzz_xdebug.ini:delegated"
      - "$PWD/php/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf:delegated"
      - "$PWD/../:/var/www:cached"
  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_PLUGINS
    labels:
      - traefik.backend={$COMPOSE_PROJECT_NAME}_adminer
      - traefik.docker.network=traefik_webgateway
      - 'traefik.frontend.rule=Host:adminer.dashtainer.localhost'
    networks:
      - app-internal
      - public
